### ISSUE TITLE
Mutability Epic

### ISSUE THREAD

**Issue by mvahowe** [mvahowe/proskomma-js#67]
# Challenges
- Mutability is a slice of GraphQL functionality that we're not yet using
- Enums are handled at a docSet level, so changes below docSet level mean reworking those enums
- Succinct representation includes context information, so a change to one block may need to be propagated forward.

# A possible order
- [x] #47 (Modify Tags) - Gets mutations working in GraphQL, does not affect succinct representation at all)
- [x] #36 (Delete DocSet - Should be easy since it removes a whole docSet so no need to unpick enums)
- [x] #34 (Add Document - append to enums)
- [x] #35 (Rehash Enums - useful for adding documents, essential for removing them)
- [x] #37 (Delete Document - requires rehash of Enums)
- [x] #66 (Modify Block - requires reworking of one or more succinct blocks)
- [x] #73 (Modify Sequence - requires gcSequence)
- [x] #75 (Add/remove block without which adding sequences is not very useful)
