### ISSUE TITLE
Generic Parsing EPIC

### ISSUE THREAD

**Issue by mvahowe** [mvahowe/proskomma-js#70]
This involves replacing the current, single, per-block Scripture-orientated parser spec with a mechanism to support multiple parser specs for different internal representations. (All these representations will use the same succinct hierarchy, but the semantics of the components and the range of graft and scope types will vary.)

# Challenges
- make underlying structure flexible while keeping it simple
- make the formats pluggable so everyone doesn't need to support everything all the time
- support 3rd party plugins
- support customization of plugins (eg extra tags in USFM)

# A possible order
- [ ] #69 (Rename Things - shouldn't break any functionality although it will break any calling code)
   - [ ] Block bs => type 
- [ ] #71 (Investigate Scripture Burrito Metadata Type System)
- [ ] #61 (Support Multiple Parser Specs)
- [ ] #65 (Replace Item Groups - this is the most immediate use case, to speed up per-verse Scripture processing)
